spring.application.name=Real_Estate_Management

#DB config
spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
#default server port 8080
#server.port=9090

# ==========================
# JWT Configuration
# ==========================
jwt.secret=myDevelopmentSecretKeyThatIsAtLeast32CharactersLong12345
jwt.expiration=86400000

# Cloudinary credentials
cloudinary.cloud-name=qdgiooxp
cloudinary.api-key=212425748213359
cloudinary.api-secret=wggUR5nVztUnWUets9crevKwYGY

# Multipart configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

